# Generated by Django 2.2.4 on 2019-09-20 09:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facegram', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ('postdate',)},
        ),
        migrations.RenameField(
            model_name='message',
            old_name='timestamp',
            new_name='postdate',
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('story', models.ImageField(upload_to='story')),
                ('postdate', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete='CASCADE', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('postdate',),
            },
        ),
    ]
