# Generated by Django 2.2.4 on 2019-09-20 09:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facegram', '0002_auto_20190920_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='actor',
            field=models.ForeignKey(on_delete='CASCADE', related_name='my_story', to=settings.AUTH_USER_MODEL),
        ),
    ]
