# Generated by Django 2.2.4 on 2019-09-20 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facegram', '0003_auto_20190920_1502'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ('timestamp',)},
        ),
        migrations.AlterModelOptions(
            name='story',
            options={},
        ),
        migrations.RenameField(
            model_name='message',
            old_name='postdate',
            new_name='timestamp',
        ),
    ]
