# Generated by Django 2.2.4 on 2019-09-20 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facegram', '0004_auto_20190920_1725'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ('postdate',)},
        ),
        migrations.RenameField(
            model_name='message',
            old_name='timestamp',
            new_name='postdate',
        ),
    ]
