# Generated by Django 2.2.4 on 2019-09-20 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facegram', '0005_auto_20190920_1730'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ('timestamp',)},
        ),
        migrations.RenameField(
            model_name='message',
            old_name='postdate',
            new_name='timestamp',
        ),
    ]
